### ISSUE TITLE
Thank you, great job, you are a gigachad

### ISSUE THREAD

**Issue by Yankovsky** [dferber90/jest-transform-css#20]
I was actually really surprised that this kind of functionality was missing from major libs.

I use this package to write react-testing-library tests like:
```jsx
render(<MyComponent className={styles.myClassName} />)
await waitFor(() => expect(screen.getByTestId('myTestId')).not.toBeVisible())
```
with css module:
```css
.myClassName {
  opacity: 0;
}
```

**Comment by dferber90** [comment]
Thanks, what a nice message at the end of the day :)
