### ISSUE TITLE
Pass jesttransformcss options in jest.config

### ISSUE THREAD

**Issue by Yankovsky** [dferber90/jest-transform-css#21]
Hey! I have monorepo structure with a slightly different jest.config for different packages, something like:
```
<root>
- package.json
- - package1
- - - jest.config.js
- - - jesttransformcss.config.js
- - package2
- - - jest.config.js
```

Now, if I run `test` command from the root dir it invokes 'test' commands in individual packages. Long story short in that configuration `jesttransformcss.config.js` is not located by the `jest-transform-css`.

I've checked [jest docs](https://jestjs.io/docs/configuration#transform-objectstring-pathtotransformer--pathtotransformer-object), and, apparently, transformer support passing options like so `{'\\.js$': ['babel-jest', {rootMode: 'upward'}]}`

Let's support passing options in jest config directly instead of providing a separate config file?

**Comment by Yankovsky** [comment]
So, it will be something like:
```
transform: {
  "^.+\\.module\\.css$": ["jest-transform-css", {modules: true}]
}
```

**Comment by dferber90** [comment]
Sounds useful, do you wanna open a PR?

**Comment by Yankovsky** [comment]
Sure. Do you want to keep both options or only the transformer options?

**Comment by Yankovsky** [comment]
It's always easier to have only one way of doing things.

**Comment by dferber90** [comment]
Agreed 👍 Let's drop the other one
