### ISSUE TITLE
I followed setup instructions and the tests are not recognizing the CSS

### ISSUE THREAD

**Issue by jordanss1** [dferber90/jest-transform-css#25]
Hey there! I am totally new to doing this kind of stuff, so I may have done something wrong.

I followed the setup and imported my CSS file into the test and it is not recognizing the CSS.

[Here](https://github.com/jordanss1/spotify-clone/blob/react-testing/jest.config.js) is my jest.config.js file

[Here](https://github.com/jordanss1/spotify-clone/blob/react-testing/src/components/__tests__/Landing.test.js) is the test file with the imported CSS.

[Here](https://github.com/jordanss1/spotify-clone/blob/react-testing/src/styles/all.css) is the CSS file

The div on line 31 of the test file has a class where the opacity is 0. So it meets the requirements of being an element that is not visible.

Yet the test is failing with this simple assertion and it is saying the element is visible, which means I believe I have not done something right in setting the jest config file up.

I am sorry if I have done something blatantly incorrect, as I am totally new to using these types of things.

Thanks

**Comment by dferber90** [comment]
It's been about 4 years since I last used this package myself, so it's hard for me to help here, sorry :/

It could be any of these things
- something is configured to change the classnames
- not sure jsdom would understand css to be able to infer visibility rules

**Comment by mryechkin** [comment]
@jordanss1 were you ever able to figure out your issue? I'm running into a similar problem - followed all the setup steps, but CSS isn't being loaded.
