### ISSUE TITLE
Sass SCSS Configuration

### ISSUE THREAD

**Issue by ghost** [dferber90/jest-transform-css#3]
We're working on a project that is using Sass (SCSS).  We like what jest-transform-css is doing for the project in the way of testing. However, it's stumbling on the files that use Sass directives because it is trying to parse the SCSS files as if they were CSS. 

Is there a configuration we can use so that jest-transform-css first runs the SCSS files through Sass' preprocessor? Or some other approach we should be taking?

Thank you. :)

**Comment by dferber90** [comment]
I replied to a similar request in https://github.com/dferber90/jest-transform-css/pull/2.

I don't plan to add anything else to this project, so maybe you could create `jest-transform-scss` based on this one?

Any possible path I see besides that would lead to either reimplementing something like webpack loaders for jest or to a feature-packed package which handles all kinds of ways to emit css (scss, less and whatever else is out there).

Hope that helps, although it's probably a bit disappointing.

**Comment by ghost** [comment]
No worries. It makes sense to keep a project focused. I hoped I had missed a simple trick to doing it. We're certainly playing with the idea of making an equivalent for scss. Your suggestion of using this project as a basis is a great idea. Thank you for your thoughts and the jest-transform-css project.

**Comment by rafinskipg** [comment]
https://www.npmjs.com/package/jest-css-modules-transform
