### ISSUE TITLE
Does not work with @font-face

### ISSUE THREAD

**Issue by MaffooBristol** [dferber90/jest-transform-css#4]
First of all, thanks for the module!

I'm getting quite close to making my `enzyme`, `jsdom-screenshot` and `jest-image-snapshot` visual regression tests look as they should, but it seems to be choking when I try and include a CSS file that has a relative @font-face declaration. The result is that the tests just time out.

I don't know if this is something at all to do with this module, but if you have any suggestions I'd very much appreciate it.

Thanks!
Matt

**Comment by dferber90** [comment]
No idea sorry. I never used `jest-transform-css` in a serious setting. I used it more to prototype and then quickly realized that a more serious visual-regresstion-testing like Percy is better solution. 

Sorry for the disappointing answer, it's a fate I had to accept as well :)

**Comment by MaffooBristol** [comment]
Thanks man. I totally understand, it's been somewhat of a pain!

My solution was actually just to base64 the font files!

Cheers 😄

**Comment by MaffooBristol** [comment]
Update for anyone interested, I actually used dferner's jest-transform-files module for the font files. It's a locally duplicated hacked version that allows for fonts and also arbitrarily excludes any files that are over 10kb:

```
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const THIS_FILE = fs.readFileSync(__filename);
// [MF] added this:
const isFont = (filename) => {
  const extname = path.extname(filename).substr(1);
  return ['ttf', 'otf', 'woff', 'woff2', 'sfnt'].indexOf(extname) > -1;
};

// copied this function from
// https://github.com/douzi8/base64-img/blob/master/base64-img.js
const base64 = (filename, data) => {
  let mimetype = 'image';
  let extname = path.extname(filename).substr(1);
  extname = extname || 'png';

  if (extname === 'svg') {
    extname = 'svg+xml';
  }

  // [MF] added these lines:
  if (isFont(filename)) {
    mimetype = 'font';
  }

  return `data:${mimetype}/${extname};base64,${data.toString('base64')}`;
};

module.exports = {
  getCacheKey: (fileData, filename, configString, { instrument }) => {
    return crypto
      .createHash('md5')
      .update(THIS_FILE)
      .update('\0', 'utf8')
      .update(fileData)
      .update('\0', 'utf8')
      .update(filename)
      .update('\0', 'utf8')
      .update(configString)
      .update('\0', 'utf8')
      .update(instrument ? 'instrument' : '')
      .digest('hex');
  },
  process: (src, filename, config, options) => {
    if (src.length > 10000 && !isFont(filename)) {
      return "module.exports = '#';";
    }
    // We could avoid reading from disk if we could use "src" directly, but I
    // could not make it work. I would like to do:
    // const data = base64(filename, Buffer.from(src));
    // But that did not work, so we use read the file for now.
    // This is an easy optimization in case somebody can make it work!
    const data = base64(filename, fs.readFileSync(filename));
    return `module.exports = ${JSON.stringify(data)};`;
  },
};
```

Additionally `const data = base64(filename, Buffer.from(src));` does actually work fine for me, it's just slower than file reads 🤔
