### ISSUE TITLE
PostCSS v8

### ISSUE THREAD

**Issue by MaffooBristol** [dferber90/jest-transform-css#8]
I'm trying to upgraded to Parcel 2 but it requires PostCSS v8, which conflicts with my use of this package, which has a dependency on PostCSS v7

How simple would it be to simply upgrade this package to use PostCSS v8?

From what I can tell, it has a [different plugin system](https://evilmartians.com/chronicles/postcss-8-plugin-migration) but still works practically the same and is backwards compatible, [according to comments on Parcel](https://github.com/parcel-bundler/parcel/issues/5152)

**Comment by MaffooBristol** [comment]
Just realised, it's Autoprefixer 10 which is causing the dependency clash, not Parcel 2

**Comment by mehiatt** [comment]
It still needs to be updated to 8.0 as there is a known issue in <8.2.13.
![image](https://user-images.githubusercontent.com/20120665/153966095-3bb9b500-09e7-49b6-afa6-f9a261e11043.png)

**Comment by dferber90** [comment]
That risk seems tolerable, as it's a development dependency.

I see the need to upgrade to postcss v8 tho 👍

**Comment by dferber90** [comment]
closed by #16
